### ISSUE TITLE
ts文件整合缓慢

### ISSUE THREAD

**Issue by zzzyyyfffzyf** [han1396735592/videoDownload#1]
<img width="469" alt="截屏2019-12-28下午7 31 18" src="https://user-images.githubusercontent.com/50076253/71542995-a522fe80-29a8-11ea-910e-7a491df63f78.png">
昨晚就开始下载并下载完成，到现在ts文件也没有整合好
多次使用都是整合比下载慢，整合开始时一秒好几个文件，到后面十分钟都没整合一个，不知是什么问题？

**Comment by han1396735592** [comment]
可以在cmd 使用命令手动进行和并  ` copy /b *.ts video.mp4`
![image](https://user-images.githubusercontent.com/29246573/71606956-5d6ec380-2bb0-11ea-9c05-bfd475675409.png)
